import {
  Activity,
  Award,
  Banknote,
  BookOpenText,
  Boxes,
  Calculator,
  CircleCheckBig,
  ClipboardCheck,
  Cog,
  Compass,
  Database,
  FileSignature,
  FolderOpen,
  Gavel,
  GitFork,
  HardHat,
  Hourglass,
  Layers,
  LineChart,
  Mail,
  Network,
  PackageSearch,
  Route,
  Scale,
  Send,
  ShieldCheck,
  Telescope,
  TrendingUp,
  TriangleAlert,
  Workflow,
  type LucideIcon,
} from 'lucide-react'

/** Resolve an icon name (string from the content model) to a Lucide component. */
const REGISTRY: Record<string, LucideIcon> = {
  Activity,
  Award,
  Banknote,
  BookOpenText,
  Boxes,
  Calculator,
  CircleCheckBig,
  ClipboardCheck,
  Cog,
  Compass,
  Database,
  FileSignature,
  FolderOpen,
  Gavel,
  GitFork,
  HardHat,
  Hourglass,
  Layers,
  LineChart,
  Mail,
  Network,
  PackageSearch,
  Route,
  Scale,
  Send,
  ShieldCheck,
  Telescope,
  TrendingUp,
  TriangleAlert,
  Workflow,
}

export function getIcon(name: string): LucideIcon {
  return REGISTRY[name] ?? Compass
}
