import type { SectionId } from '../types'

export interface DeckSlide {
  id: string
  part: 0 | 1 | 2
  kind?: 'title' | 'agenda' | 'content' | 'recap' | 'closing'
  kicker?: string
  title: string
  subtitle?: string
  bullets?: string[]
  columns?: { heading: string; items: string[] }[]
  note?: string
  visual: string
  /** link to the matching "full explanation" lecture notes */
  lecture?: SectionId
}

/* The deck — every topic in presentation order (Part 1 → Part 2). */
export const SLIDES: DeckSlide[] = [
  // ───────────────────────── PART 1 ─────────────────────────
  {
    id: 's-title-1',
    part: 1,
    kind: 'title',
    kicker: 'MRICS & AIQS APC Coaching',
    title: 'Commercial Management in Construction',
    subtitle: 'Part 1 · Pre-Contract — presented by Roshan de Silva',
    visual: 'hero',
  },
  {
    id: 's-agenda-1',
    part: 1,
    kind: 'agenda',
    kicker: 'Part 1',
    title: 'Agenda',
    bullets: [
      'About the competency (RICS vs AIQS)',
      'Competency mapping',
      'What & Why',
      'Pre-contract commercial management',
      'Preselection phase',
      'Decision to Tender',
      'Project Appreciation',
      'Estimating the works',
      'Tender Adjudication',
      'Tender Submission / post-tender dealings',
      'Recap',
    ],
    visual: 'agenda',
  },
  {
    id: 's-rics',
    part: 1,
    kicker: 'About the Competency',
    title: 'RICS Competency',
    columns: [
      { heading: 'Mandatory', items: ['L3 · Ethics & professionalism', 'L2 · Client care; Comms; H&S', 'L1 · Accounting, business planning, sustainability …'] },
      { heading: 'Core (L3)', items: ['Commercial management of construction works', 'Construction technology', 'Contract practice', 'Procurement & tendering', 'Project finance; Quantification'] },
      { heading: 'Optional (2 → L2)', items: ['Capital allowances', 'Contract administration', 'Insurance; Due diligence', 'Risk management; Programming …'] },
    ],
    note: 'Commercial/contracting experience → take Commercial Management to Level 3.',
    visual: 'competency',
    lecture: 'competency',
  },
  {
    id: 's-aiqs',
    part: 1,
    kicker: 'About the Competency',
    title: 'AIQS Framework',
    bullets: [
      'Commercial Management is unit 8, under Contract Documentation & Procurement.',
      '38 units across 6 competency groups.',
    ],
    columns: [
      { heading: 'Project Cost Management', items: ['Design Cost Advice & Planning', 'Contract Documentation & Procurement ★', 'Contract Administration'] },
      { heading: 'Wider groups', items: ['Support Competencies', 'Asset Financial Management', 'Specialised Management', '+ General & Soft Skills'] },
    ],
    visual: 'aiqs',
    lecture: 'competency',
  },
  {
    id: 's-mapping',
    part: 1,
    kicker: 'Competency Mapping',
    title: 'MRICS vs MAIQS',
    columns: [
      { heading: 'MRICS pathway', items: ['Design Economics & Cost Planning', 'Procurement & Tendering', 'Commercial Management (Pre & Post)', 'Contract Practice & Administration', 'Project Finance'] },
      { heading: 'MAIQS pathway', items: ['Design Cost Advice & Cost Engineering', 'Contract Documentation & Procurement', 'Contract Administration'] },
    ],
    note: 'Commercial Management threads through cost, procurement, contract & finance in both frameworks.',
    visual: 'map',
    lecture: 'competency',
  },
  {
    id: 's-whatwhy',
    part: 1,
    kicker: 'What & Why',
    title: 'Secure, then Enhance',
    bullets: [
      'A process to firstly secure the intended profit, then enhance it.',
      'Spans both pre-contract and post-contract stages.',
      'Client chases value for money; the contractor chases profit — never mix the two.',
    ],
    note: 'Intended profit = the margin priced over the cost (e.g. 10%). CM lifts the realised margin above it.',
    visual: 'securenhance',
    lecture: 'overview',
  },
  {
    id: 's-precontract',
    part: 1,
    kicker: 'Pre-Contract Commercial Management',
    title: 'The Pre-Contract Journey',
    bullets: [
      '1 · Preselection phase',
      '2 · Decision to Tender',
      '3 · Project Appreciation',
      '4 · Estimating the works',
      '5 · Tender Adjudication',
      '6 · Tender Submission / post-tender dealings',
    ],
    visual: 'lifecycle-pre',
    lecture: 'precontract',
  },
  {
    id: 's-preselection',
    part: 1,
    kicker: 'Stage 1',
    title: 'Preselection Phase',
    bullets: [
      'Prequalification — submit documents proving technical & financial competence.',
      'Generally: 3 years of audited financials (P&L, balance sheet, auditor’s statement).',
      'Submit with technical prequalification; attend a client interview if needed.',
    ],
    note: 'Why 3 years? It shows the financial trend — proof the contractor can fund the works until paid.',
    visual: 'docs',
    lecture: 'precontract',
  },
  {
    id: 's-decision',
    part: 1,
    kicker: 'Stage 2',
    title: 'Decision to Tender',
    bullets: [
      'Respond first — accept, or send a regret letter.',
      'Collect documents; prepare a preliminary report (scope, client, location, experience).',
      'Weigh workload, profitability, resources, the timeframe — and the business plan.',
    ],
    columns: [
      { heading: 'Relies upon', items: ['Client/consultant relationship', 'Work type & value', 'Current workload & profitability', 'Resources & tender timeframe', 'Competition & risk assessment'] },
    ],
    visual: 'decision',
    lecture: 'precontract',
  },
  {
    id: 's-appreciation',
    part: 1,
    kicker: 'Stage 3',
    title: 'Project Appreciation',
    columns: [
      { heading: 'Check list', items: ['Tender procedure', 'Lead estimator & PM/CM', 'Programme & deadline', 'Method statements; histograms', 'Pricing strategy; site visits'] },
      { heading: 'Site visits', items: ['Location & surroundings', 'Demolitions; soil & access', 'Dumping / borrow pits', 'Who else attends (competition)'] },
      { heading: 'Schedules', items: ['Material & labour', 'Specialist subs & suppliers', 'Subcontract & plant'] },
    ],
    note: 'Front / back / spot loading are unethical — never present them as your pricing strategy.',
    visual: 'appreciation',
    lecture: 'precontract',
  },
  {
    id: 's-est-data',
    part: 1,
    kicker: 'Stage 4 · Estimating',
    title: 'Schedules of Data',
    bullets: [
      'In-house cost databases — ensure relevance, adjust as necessary.',
      'First principles — build rates from scratch: material + labour + plant + subcontractor.',
      'Supplier / subcontractor quotes.',
      'Operational estimates.',
    ],
    visual: 'costbuildup',
    lecture: 'estimating',
  },
  {
    id: 's-est-quotes',
    part: 1,
    kicker: 'Stage 4 · Estimating',
    title: 'Quotes & Operational Estimates',
    columns: [
      { heading: 'Every enquiry states', items: ['Project title & location', 'Work description & specs', 'Quality; delivery period', 'Contractor facilities', 'Date required; validity'] },
      { heading: 'Operational estimate', items: ['Costed by operation/activity', 'From a work study / experience', 'Benchmark for future tenders'] },
    ],
    visual: 'quote',
    lecture: 'estimating',
  },
  {
    id: 's-est-risks',
    part: 1,
    kicker: 'Stage 4 · Estimating',
    title: 'Estimating Risks',
    columns: [
      { heading: 'Procurement / contract', items: ['Traditional, D&B, MC, CM', 'Remeasure, lump sum', 'Cost reimbursement: cost+%, target, GMP'] },
      { heading: 'Common', items: ['Lack of drawings & specs', 'BOQ accuracy', 'Duration & LDs; price fixity'] },
      { heading: 'Market & site', items: ['Price fluctuation, labour, visas', 'Technical & buildability'] },
    ],
    note: 'Risk can be reduced by issuing tender queries to the employer.',
    visual: 'risk',
    lecture: 'estimating',
  },
  {
    id: 's-est-managerisk',
    part: 1,
    kicker: 'Stage 4 · Estimating',
    title: 'Managing the Risk',
    bullets: [
      'Risk workshop (major projects) → prepare a risk register, categorise by likelihood & impact.',
      'Quantitative risk analysis (probability × impact); allow a risk contingency budget.',
      'Pre-bid agreement — lock a supplier’s price in exchange for an award commitment.',
      'Joint venture / consortium to distribute risk.',
    ],
    visual: 'shield',
    lecture: 'estimating',
  },
  {
    id: 's-adjudication',
    part: 1,
    kicker: 'Stage 5',
    title: 'Tender Adjudication',
    bullets: [
      'A commercial-judgement meeting converting the estimate (cost) into the tender price.',
      'Applies head office overhead, profit (per the business plan) and a risk allowance.',
      'Overheads = site overheads (in prelims) + head office overheads.',
    ],
    columns: [
      { heading: 'Head office overheads', items: ['Salaries, rent, utilities', 'Insurance & bank charges', 'Tender docs; audit & legal fees', 'Recruitment; unrecoverable debts'] },
    ],
    visual: 'adjudication',
    lecture: 'tender',
  },
  {
    id: 's-submission',
    part: 1,
    kicker: 'Stage 6',
    title: 'Tender Submission',
    columns: [
      { heading: 'Technical', items: ['Trade licence; form of tender', 'Project profile; execution plan', 'Method statement; programme', 'Org chart; key CVs', 'QC & HSE; labour histogram'] },
      { heading: 'Commercial', items: ['Covering letter (offer price)', 'Qualifications / exclusions', 'Form of tender; priced BOQs', 'Schedule of rates; day-works'] },
    ],
    note: 'Technical evaluated first (~75% cut-off) → then commercial. Then BAFO/LAFO & post-tender dealings.',
    visual: 'submission',
    lecture: 'tender',
  },
  {
    id: 's-recap-1',
    part: 1,
    kind: 'recap',
    kicker: 'Part 1',
    title: 'Recap',
    bullets: [
      'Commercial Management is a contractor’s competency — profit, not value for money.',
      'Competency & mapping across RICS and AIQS.',
      'Pre-contract: preselection → decision → appreciation → estimating → adjudication → submission.',
      'Secure the intended profit; set up to enhance it post-contract.',
    ],
    visual: 'recap',
  },

  // ───────────────────────── PART 2 ─────────────────────────
  {
    id: 's-title-2',
    part: 2,
    kind: 'title',
    kicker: 'MRICS & AIQS APC Coaching',
    title: 'Commercial Management in Construction',
    subtitle: 'Part 2 · Post-Contract',
    visual: 'hero',
  },
  {
    id: 's-agenda-2',
    part: 2,
    kind: 'agenda',
    kicker: 'Part 2',
    title: 'Agenda',
    bullets: [
      'About the competency (refresher)',
      'Competency mapping',
      'What & Why',
      'Post-contract commercial management',
      'Profit Enhancement',
      'Procurement',
      'Reporting',
      'Contract Administration',
      'Recap',
    ],
    visual: 'agenda',
  },
  {
    id: 's-postcontract',
    part: 2,
    kicker: 'Post-Contract Commercial Management',
    title: 'The Post-Contract Journey',
    bullets: [
      '1 · Profit Enhancement',
      '2 · Procurement',
      '3 · Reporting',
      '4 · Contract Administration',
    ],
    note: 'Beneath it all: balance risks against opportunities — upstream (client) and downstream (subs).',
    visual: 'lifecycle-post',
    lecture: 'postcontract',
  },
  {
    id: 's-profit-balance',
    part: 2,
    kicker: 'Profit Enhancement',
    title: 'Risks ⚖ Opportunities',
    bullets: [
      'Profit enhancement = an appropriate balance between risks and opportunities.',
      'For every risk you carry, find an opportunity to offset it.',
    ],
    visual: 'balance',
    lecture: 'profit',
  },
  {
    id: 's-profit-risks',
    part: 2,
    kicker: 'Profit Enhancement',
    title: 'The Risks',
    bullets: [
      'Authorities — permit & approval delays (often poorly mitigated).',
      'Design — incomplete / inadequate design.',
      'Services — availability & reliability of utilities.',
      'HSE — safety, environment, regulatory compliance.',
      'Contractual — disputes; contract type & fluctuation exposure.',
    ],
    visual: 'risk',
    lecture: 'profit',
  },
  {
    id: 's-profit-opps',
    part: 2,
    kicker: 'Profit Enhancement',
    title: 'The Opportunities',
    bullets: [
      'Early completion — save the preliminaries on the months saved.',
      'Buying gains — economies of scale (bulk → lower rates).',
      'Reducing running costs — water, power, fuel, pantry.',
      'Increasing productivity — right-fit, trade-specific resources.',
      'Value engineering — cost savings without losing functionality.',
    ],
    visual: 'opportunities',
    lecture: 'profit',
  },
  {
    id: 's-bulk',
    part: 2,
    kicker: 'Profit Enhancement',
    title: 'Bulk Buying — Only If…',
    bullets: [
      'The contractor can afford the upfront expense.',
      'Multiple concurrent projects share the same specification (e.g. rebar).',
      'Inventory control can track quantities per project.',
      'Storage cost is low.',
    ],
    note: 'Great commercial rate — but it ties up cash, so it can hit the cash flow.',
    visual: 'boxes',
    lecture: 'profit',
  },
  {
    id: 's-registers',
    part: 2,
    kicker: 'Profit Enhancement',
    title: 'R&O Register',
    columns: [
      { heading: 'Common risks', items: ['Market & price volatility', 'Labour shortages', 'Weather; safety incidents', 'Change orders; payment issues'] },
      { heading: 'Common opportunities', items: ['Value engineering', 'Buying gains; early completion', 'Negotiations; scope management', 'Cost monitoring; quality'] },
    ],
    note: '3-tier probabilistic assessment (worst / expected / best). Delta (opps − risks) feeds the CTC.',
    visual: 'register',
    lecture: 'profit',
  },
  {
    id: 's-proc-materials',
    part: 2,
    kicker: 'Procurement',
    title: 'Materials',
    bullets: [
      'Detailed schedule: local vs foreign, long- vs short-lead, purpose-made vs standard.',
      'Lean on the central procurement team — they have the supplier connections.',
      'Maintain a tracker for monitoring and control.',
    ],
    visual: 'materials',
    lecture: 'procurement',
  },
  {
    id: 's-proc-labour',
    part: 2,
    kicker: 'Procurement',
    title: 'Labour',
    bullets: [
      'Brainstorm with execution: why can’t in-house labour deliver?',
      'Decide general vs trade-specific subcontracting.',
      'Issue RFQs → evaluate → negotiate → award → administer.',
    ],
    visual: 'labour',
    lecture: 'procurement',
  },
  {
    id: 's-proc-sub',
    part: 2,
    kicker: 'Procurement',
    title: 'Subcontracts',
    bullets: [
      'Subcontracting schedule; procurement & contract strategy.',
      'Open (find & enquire, no prequal), selective (judge by track record), or negotiated.',
      'QS evaluates only the commercial side — not the technical.',
    ],
    note: '“Discount” is banned in APC — use “negotiate for budget-aligned gains” (give & take).',
    visual: 'network',
    lecture: 'procurement',
  },
  {
    id: 's-proc-docs',
    part: 2,
    kicker: 'Procurement',
    title: 'Tender Documents',
    columns: [
      { heading: 'Five volumes', items: ['I · Conditions', 'II · Specifications', 'III · Drawings', 'IV · BOQ', 'V · Soil report'] },
      { heading: 'Procurement route', items: ['Traditional', 'Design & Build', 'Management Contracting (seldom)', 'Construction Management (seldom)'] },
    ],
    visual: 'volumes',
    lecture: 'procurement',
  },
  {
    id: 's-report-overview',
    part: 2,
    kicker: 'Reporting',
    title: 'Four Reports',
    bullets: [
      'Cash Flow · CVR · CTC — the three core QS reports.',
      'Earned Value Analysis — really project controls / planning.',
      'Reporting drives competent, efficient, compliant, profit-focused decisions.',
    ],
    visual: 'reports',
    lecture: 'reporting',
  },
  {
    id: 's-cashflow',
    part: 2,
    kicker: 'Reporting',
    title: 'Cash Flow',
    bullets: [
      'Cash in (revenue) vs cash out (cost); the delta is profit.',
      'Two types: organisational and project-specific.',
      'Prepare it from project award, then keep it recurring.',
    ],
    visual: 'cashflow',
    lecture: 'reporting',
  },
  {
    id: 's-cashflow-methods',
    part: 2,
    kicker: 'Reporting · Cash Flow',
    title: 'Three Methods',
    bullets: [
      '1 · Equal apportioning — contract sum ÷ duration (basic).',
      '2 · ¼–½–¼ method — first third ¼ of cost, middle ½, last ¼ → the S-curve.',
      '3 · Programme-based — the accurate method.',
    ],
    note: 'Programme method needs: construction programme + conditions of contract (payment timing); BOQ optional.',
    visual: 'cashflow',
    lecture: 'reporting',
  },
  {
    id: 's-negcash',
    part: 2,
    kicker: 'Reporting · Cash Flow',
    title: 'Negative Cash Flow',
    bullets: [
      'Request ad-hoc / advance payment (against an APG).',
      'Negotiate extended supply-chain credit; reduce overheads.',
      'Increase the rate of progress; release retention via a bond.',
      'Corporate cash; short-term bank finance as a last resort.',
    ],
    visual: 'cashflow',
    lecture: 'reporting',
  },
  {
    id: 's-ctc',
    part: 2,
    kicker: 'Reporting',
    title: 'Cost to Complete (CTC)',
    bullets: [
      'CTC = actual cost to date + forecast cost of the balance works.',
      'Compared vs the final account (revenue) and the original budget.',
      'Actual from the ledger; forecast by the QS/CM with planning & ops.',
    ],
    note: 'e.g. 3 months in: 300k incurred + 800k forecast = 1.1M, benchmarked to budget & revenue.',
    visual: 'ctc',
    lecture: 'reporting',
  },
  {
    id: 's-cvr',
    part: 2,
    kicker: 'Reporting',
    title: 'Cost Value Reconciliation',
    bullets: [
      'In-period movement — the profit/loss earned this period; the project P&L.',
      'Cost: ledger + accruals/provisions + subcontractor liability.',
      'Value: interim payment application or certificate, with adjustments.',
    ],
    note: 'Material on site is EXCLUDED — it’s an advance payment; counting it double-counts the value.',
    visual: 'cvr',
    lecture: 'reporting',
  },
  {
    id: 's-admin',
    part: 2,
    kicker: 'Contract Administration',
    title: 'Upstream & Downstream',
    bullets: [
      'Upstream = the contract with the client; downstream = the supply chain.',
      'Interim valuations, variations and claims in both directions.',
      'Settle the final accounts.',
    ],
    visual: 'admin',
    lecture: 'admin',
  },
  {
    id: 's-recap-2',
    part: 2,
    kind: 'recap',
    kicker: 'Part 2',
    title: 'Recap',
    bullets: [
      'Post-contract: profit enhancement, procurement, reporting, contract administration.',
      'Profit enhancement blends risks and opportunities.',
      'Reporting: cash flow (3 methods), CVR and CTC.',
      'Administer upstream and downstream.',
    ],
    visual: 'recap',
  },
  {
    id: 's-soe',
    part: 0,
    kicker: 'Write Your APC',
    title: 'Sample SOEs',
    bullets: [
      'Three worked Commercial Management Summaries of Experience — structured across Levels 1, 2 and 3.',
      'SOE 1 · Estimating & Tender Adjudication (pre-contract).',
      'SOE 2 · Cost Reporting — CVR & Cost to Complete (post-contract).',
      'SOE 3 · Subcontract Procurement & Risk (post-contract).',
    ],
    note: 'Read the full text in Explore mode → “Sample SOEs”. Models only — never copy; evidence your real projects.',
    visual: 'submission',
  },
  {
    id: 's-closing',
    part: 0,
    kind: 'closing',
    kicker: 'Thank you',
    title: 'You’ve covered it all',
    subtitle: 'APC Coaching · apccoaching.me',
    bullets: [
      'Now reinforce with the flashcards and the quiz in Explore mode.',
      'Each slide links to the full lecture explanation.',
    ],
    visual: 'thanks',
  },
]
